### ISSUE TITLE
一些疑问和建议

### ISSUE THREAD

**Issue by xcenweb** [GeniusLe/PHP-Autoloader#1]
我按照 _README.md_ 的指示将类文件部署到了我的项目。
为了适应项目需要我修改了类文件和类名称及相关内容。

```php

....(include class file)

spl_autoload_register("Loader::autoloader");
Loader::set_error(true);
Loader::set_root_dir(APP_PATH);
Loader::add("gugu\\core\\", "core/");
new gugu\core\debug();

```

然后程序运行时报错:

```

Fatal error: Uncaught Error: Class 'gugu\core\debug' not found in ... Stack trace: #0 ...: include() #1 {main} thrown in ... on line ...

```
可能是我第一次来研究autoload吧，我找不到问题的根本原因，网上搜索一通也找不着例子(官网例子太生涩难懂了)。劳烦大佬能将描述说详细一点 :)

**Comment by GeniusLe** [comment]
抱歉我关闭了这个项目的提示，所以我没有看到你的问题，从你贴的报错来讲 你应该是你的类的类名空间不正确
首先这个报错表明自动加载已经根据你提供的类名空间自动载入成功了
检查你的代码是否为
'''php
<?php
namespace gugu\core;
class debug{
}

?>
'''
否则即使自动载入 也会因为你文件内没有相关类而导致错误产生

**Comment by xcenweb** [comment]
非常感谢！问题解决了！😃
